const VersionActionTypes = {
  FETCH_VERSIONS_START : 'FETCH_VERSIONS_START',
  FETCH_VERSIONS_SUCCESS : 'FETCH_VERSIONS_SUCCESS',
  FETCH_VERSIONS_FAILURE : 'FETCH_VERSIONS_FAILURE'
}

export default VersionActionTypes