const DesignActionTypes = {
  FETCH_DESIGNS_START : 'FETCH_DESIGNS_START',
  FETCH_DESIGNS_SUCCESS : 'FETCH_DESIGNS_SUCCESS',
  FETCH_DESIGNS_FAILURE : 'FETCH_DESIGNS_FAILURE'
}

export default DesignActionTypes